export const ProjectsData = [
  {
    title: "Patrimônio-Website",
    description: "Web tool for asset control and organization, utilizing QR Code and NFC scanning technology.",
    completeDescription: "This project is a web-based asset management and control system developed to support the administrative and logistical operations of the Public Defender’s Office of the Federal District (DPDF). \n\nThe platform enables efficient tracking, organization, and monitoring of institutional assets through the use of QR Code and NFC technologies, allowing users to quickly identify and retrieve asset information by scanning tags directly from the interface.",
    myContribution: "In this project, I was responsible for developing the front-end using React.js and Tailwind.css. I implemented key features such as asset registration, search functionality, and real-time status updates. Additionally, I collaborated closely with the back-end team to ensure seamless integration with the database and API services.",
    image: "../../projetos/patri.svg",
    image_2: "../../projetos/patri_2.svg",
    imageSize: "w-[50%]",
    imageSizeModal: "w-[35%] md:w-[30%]",
    techs: [
      { id: 1, image: "icones/SQLServer_Logo.svg" },
      { id: 2, image: "icones/Next_Logo.svg" },
      { id: 3, image: "icones/Tailwind_Logo.svg" },
      { id: 4, image: "icones/Docker_Logo.svg" },
      { id: 5, image: "icones/React_Logo.svg" },
      { id: 6, image: "icones/HeroUI_Logo.png" },
      { id: 7, image: "icones/Type_Logo.svg" },
    ]
  },
  {
    title: "Eclipse",
    description: "Data collection and management platform designed to streamline and optimize internal processes within the Public Defender’s Office of the Federal District (DPDF).",
    completeDescription: "This project is a data collection and workflow management platform designed to support and optimize internal evaluation processes within the Public Defender’s Office of the Federal District (DPDF). \n\n The system specifically assists in the probationary assessment of public defenders, providing a structured, transparent, and automated environment for evaluating their professional performance.",
    image: "../../projetos/Eclipse.svg",
    image_2: "../../projetos/Eclipse_2.svg",
    imageSize: "w-[50%]",
    imageSizeModal: "w-[50%]",
    techs: [
      { id: 1, image: "icones/Mongo_Logo.svg" },
      { id: 2, image: "icones/Next_Logo.svg" },
      { id: 3, image: "icones/Tailwind_Logo.svg" },
      { id: 4, image: "icones/Docker_Logo.svg" },
      { id: 5, image: "icones/React_Logo.svg" },
      { id: 6, image: "icones/HeroUI_Logo.png" },
      { id: 7, image: "icones/Type_Logo.svg" },
    ],
  },
  {
    title: "Vroomly (In Construction)",
    description: " In Construction",
    completeDescription: "In Construction",
    image: "../../projetos/Vroomly.png",
    image_2: "",
    imageSize: "w-[80%]",
    imageSizeModal: "w-[40%]",
    techs: [
      { id: 1, image: "icones/Postgres_Logo.svg" },
      { id: 2, image: "icones/Next_Logo.svg" },
      { id: 3, image: "icones/Tailwind_Logo.svg" },
      { id: 4, image: "icones/Docker_Logo.svg" },
      { id: 5, image: "icones/React_Logo.svg" },
      { id: 6, image: "icones/HeroUI_Logo.png" },
      { id: 7, image: "icones/Type_Logo.svg" },
      { id: 8, image: "icones/Motion_Logo.svg" },
    ]
  },
]